version: '3.8'
services:
  fronend-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
       - .:/app
    command: ["npm", "run", "test"]